language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

after_script: cp dist/index.html dist/404.html

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: master
